version: "3.9"

services:
    web:
        image: nginx:latest
        restart: always
        links:
            - app:php
        working_dir: /var/www
        volumes:
            - ./../:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    app:
        build:
            context: ./php
        restart: always
        working_dir: /var/www
        links:
            - db:mysql
        volumes:
            - ./../:/var/www/

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: laminar
            MYSQL_USER: lami
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - laminar:/var/lib/mysql
volumes:
    laminar:

